controller_list:
  - name: fake_duco_gcr10_2000_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: duco_gcr10_2000
    pose: home